apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.certificate.name }}
spec:
  dnsNames:
    - {{ .Values.ingress.host }}
  secretName: {{ .Values.certificate.secretname }}
  issuerRef:
    name: {{ .Values.clusterIssuer.name }}
    kind: ClusterIssuer